### ISSUE TITLE
Serious problem introduced when libdw was adopted

### ISSUE THREAD

**Issue by jmellorcrummey** [dyninst/dyninst#415]
When using Symtab::openFile to open a binary for hpcstruct, after the switch to libdw, something is horribly wrong. Instead of each function having a modest number of address ranges, every file now has 7000 address ranges associated with it. When DYNINST_DEBUG_DWARF and COMMON_DEBUG_DWARF are set to 1, the switch to libdw increases the output by a factor of 44. 

After 

```
commit 901ebfbe2dded83ddba9c3cd179713af44d60d8d
Merge commit 'd0160a8' into v9.3.x
```
things are fine.

However, after 

```
commit 38e17c89ba4a76329ffd11ebcfec379a04c64b7a
Fixing small things after the merge.

```

a cleanup commit following the addition of libdw, the blowup occurs. This is the first commit after the libdw commit 

```
commit e0b9befe7b8a03ff918b00132f496eea9398dec4
Merge branch 'sasha/libdw_deploy' into v9.3.x
```
that builds.

Tar file for the test case, and the input, which includes differing output for the good and bad commit versions, is attached.  

If you grep the two output files in my attached example, for a filename or two, e.g., Args.cpp and main.cpp, you will see that for version 901ebfbe2dded83ddba9c3cd179713af44d60d8d (the good commit),  you will see the following:
```
 grep main.cpp version-901ebfbe2dded83ddba9c3cd179713af44d60d8d.log | wc
     17     119    1853
 grep Args.cpp version-901ebfbe2dded83ddba9c3cd179713af44d60d8d.log | wc
     27     189    2943
```

For the problematic version 38e17c89ba4a76329ffd11ebcfec379a04c64b7a, you will see the following:

```
grep main.cpp version-38e17c89ba4a76329ffd11ebcfec379a04c64b7a.log | wc
   7000   49000  763000
grep Args.cpp version-38e17c89ba4a76329ffd11ebcfec379a04c64b7a.log | wc
   7000   49000  763000
```

[open-regression-test.tar.gz](https://github.com/dyninst/dyninst/files/1413195/open-regression-test.tar.gz)

**Comment by jmellorcrummey** [comment]
I don't know whether you get notified about these automatically if they aren't tagged. So, here I am adding tags. @sashanicolas @wrwilliams

**Comment by wrwilliams** [comment]
We're doing some range info parsing wrong on master; this is fixed on new-parallel-parsing. I can extract the changes and merge them over if need be.

**Comment by mxz297** [comment]
I tried to extract Bill's fix on this issue from the new-parallel-parsing branch for other reasons. It is in pull request #408 and should be fine to merge. 

@sashanicolas Could you merge #408 and make sure it will resolve John's reported issue?

**Comment by sashanicolas** [comment]
@jmellorcrummey I tested it and I got the results of libdwarf, as you expected. I have merged the fix into master. 
We still see some ranges that might not be reasonable (and some were present with libdwarf), but for now the ranges explosion is fixed.

**Comment by jmellorcrummey** [comment]
I ran my regression test and also hpcstruct on hpcstruct-bin. Before the fix, running hpcstruct on hpcstruct-bin died after filling up memory in my VirtualBox (which was only a few GB).  Now, both work fine for me again. Thanks!
